ITI.Survey.Web/ITI.Survey.Web.UI/Controllers/ContainerDurationController.cs
using AGY.Solution.Helper;
using AGY.Solution.Helper.Common;
using ITI.Survey.Web.UI.Models;
using ITI.Survey.Web.UI.StackingWebService;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;

namespace ITI.Survey.Web.UI.Controllers
{
    [Authorize]
    public class ContainerDurationController : BaseController
    {
        // GET: ContainerDuration
        public ActionResult Index()
        {
            ContainerDurationModel model = new ContainerDurationModel();
            GetConfigXML();
            return View(model);
        }

        [NonAction]
        IList<ContainerDurationModel> DataContainerDuration(string userId, string customerCode, string size, string type, string condition, int minDuration, string sortBy)
        {
            IList<ContainerDurationModel> result = new List<ContainerDurationModel>();

            using (var stackingService = new StackingSoapClient())
            {
                string xml = stackingService.FillContainerDuration(userId, customerCode, size, type, condition, minDuration, sortBy);
                if (!string.IsNullOrWhiteSpace(xml) || !xml.Contains("Error"))
                {
                    DataSet dataSet = Converter.ConvertXmlToDataSet(xml);
                    DataTable dataTable = dataSet.Tables[0];
                    result = dataTable.ToList<ContainerDurationModel>();
                }
            }
            return result;
        }

        [HttpPost]
        public ActionResult DataTableContainerDuration(ContainerDurationModel objSearch)
        {
            DataTableModel objPage = new DataTableModel { CurrentPage = 1, IsDescending = true, PageSize = int.MaxValue, PropertyOrder = "Cont" };
            IList<ContainerDurationModel> resultSearch = DataContainerDuration(Username, objSearch.CustomerCode, objSearch.Size, objSearch.Type, objSearch.Condition, objSearch.Duration, objPage.PropertyOrder);
            objPage.TotalRow = resultSearch.Count;
            ViewBag.Pagination = PageHelper.CreateLink(objPage.CurrentPage, objPage.TotalRow, objPage.PageSize, true);
            return View("_DataTableContainerDuration", resultSearch);
        }
    }
}

ITI.Survey.Web/ITI.Survey.Web.UI/Views/ContainerDuration/Index.cshtml

@{
    ViewBag.Title = "CONTAINER DURATION";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model ITI.Survey.Web.UI.Models.ContainerDurationModel

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <b>CONTAINER DURATION</b>
            </div>
            <div class="panel-body">
                <div class="form-horizontal">
                    <div class="row">
                        <div class="col-md-12">
                            <form action="@Url.Action("DataTableContainerDuration", "ContainerDuration")" method="post">
                                @Html.AntiForgeryToken()
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <div class="col-md-3">
                                                @Html.LabelFor(model => model.CustomerCode, htmlAttributes: new { @class = "control-label" })
                                            </div>
                                            <div class="col-md-7">
                                                @Html.DropDownListFor(model => model.CustomerCode, (IEnumerable<SelectListItem>)ViewBag.Customers, new { @class = "form-control" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <div class="col-md-3">
                                                <label class="control-label">MIN DURATION</label>
                                            </div>
                                            <div class="col-md-7">
                                                <input type="text" id="Duration" name="Duration" class="form-control" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <div class="col-md-3">
                                                @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label" })
                                            </div>
                                            <div class="col-md-7">
                                                @Html.DropDownListFor(model => model.Size, (IEnumerable<SelectListItem>)ViewBag.ContainerSize, new { @class = "form-control" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <div class="col-md-3">
                                                @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label" })
                                            </div>
                                            <div class="col-md-7">
                                                @Html.DropDownListFor(model => model.Type, (IEnumerable<SelectListItem>)ViewBag.ContainerType, new { @class = "form-control" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <div class="col-md-3">
                                                <label class="control-label">CONDITION</label>
                                            </div>
                                            <div class="col-md-7">
                                                <input type="text" id="Condition" name="Condition" class="form-control" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <div class="col-md-3 col-md-offset-3">
                                                <button type="button" class="btn btn-primary btn-search" data-hidden=""
                                                        data-skip="ContInOutId,ActIn,RfEngineCond,EorNo,DtmEor,DtmApproved,DtmCompleted,RepairStatus,SpecialMessage2"
                                                        data-property-order="Cont" data-pagesize="@int.MaxValue">
                                                    <span><i class="fa fa-search"></i> Search </span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div class="data-result">
                        @Html.Partial("_DataTableContainerDuration", new List<ITI.Survey.Web.UI.Models.ContainerDurationModel>())
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>

ITI.Survey.Web/ITI.Survey.Web.UI/Views/ContainerDuration/_DataTableContainerDuration.cshtml
@{ 
    Layout = null;
}

@model IEnumerable<ITI.Survey.Web.UI.Models.ContainerDurationModel>

<div class="col-xs-12">
    <div class="form-group">
        <input type="hidden" class="current-page" value="1" />
        @*<div class="table-responsive">*@
            <table class="table table-striped table-bordered dataTable" width="100%">
                <thead>
                    <tr>
                        <th data-id="No" data-desc="True">
                            @Html.DisplayNameFor(model => model.No)
                        </th>
                        <th data-id="Cont" data-desc="True">
                            @Html.DisplayNameFor(model => model.Cont)
                        </th>
                        <th data-id="Size" data-desc="True">
                            @Html.DisplayNameFor(model => model.Size)
                        </th>
                        <th data-id="Type" data-desc="True">
                            @Html.DisplayNameFor(model => model.Type)
                        </th>
                        <th data-id="CustomerCode" data-desc="True">
                            @Html.DisplayNameFor(model => model.CustomerCode)
                        </th>
                        <th data-id="Condition" data-desc="True">
                            @Html.DisplayNameFor(model => model.Condition)
                        </th>
                        <th data-id="DtmIn" data-desc="True">
                            @Html.DisplayNameFor(model => model.DtmIn)
                        </th>
                        <th data-id="Duration" data-desc="True">
                            @Html.DisplayNameFor(model => model.Duration)
                        </th>
                        <th data-id="Remarks" data-desc="True">
                            @Html.DisplayNameFor(model => model.Remarks)
                        </th>
                        <th data-id="SpecialMessage" data-desc="True">
                            @Html.DisplayNameFor(model => model.SpecialMessage)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.No)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Cont)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Size)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Type)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CustomerCode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Condition)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DtmIn)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Duration)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Remarks)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SpecialMessage)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            @*<div class="dt-toolbar-footer">
                <div class="col-xs-12 col-sm-12">
                    <div class="dataTables_paginate paging_simple_numbers">
                        @Html.Raw(ViewBag.Pagination)
                    </div>
                </div>
            </div>
        </div>*@
    </div>
</div>