ITI.Survey.Web/ITI.Survey.Web.UI/Controllers/SearchContainerController.cs
using AGY.Solution.Helper;
using AGY.Solution.Helper.Common;
using ITI.Survey.Web.UI.Models;
using ITI.Survey.Web.UI.StackingWebService;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;

namespace ITI.Survey.Web.UI.Controllers
{
    [Authorize]
    public class SearchContainerController : BaseController
    {
        // GET: SearchContainer
        public ActionResult SearchContainerByContNo()
        {
            SearchContainerModel model = new SearchContainerModel();
            return View(model);
        }
        public ActionResult SearchContainerByKodeBlok()
        {
            SearchContainerModel model = new SearchContainerModel();
            return View(model);
        }
        [NonAction]
        IList<SearchContainerModel> SearchContainerByContNo(string userId, string containerNumber)
        {
            IList<SearchContainerModel> result = new List<SearchContainerModel>();
            string contnumber = containerNumber.Trim().ToUpper().Replace(" ", "");
            while (contnumber.Length < 11)
            {
                contnumber = contnumber + " ";
            }
            contnumber = contnumber.Substring(0, 4) + " " + contnumber.Substring(4, 3) + " " + contnumber.Substring(7, 3) + " " + contnumber.Substring(10, 1);
            contnumber = contnumber.Trim();
            using (var stackingService = new StackingSoapClient())
            {
                string xml = stackingService.FillContInOutByContainerForStock(userId, contnumber);
                if (!string.IsNullOrEmpty(xml))
                {
                    DataSet dataSet = Converter.ConvertXmlToDataSet(xml);
                    DataTable dataTable = dataSet.Tables[0];
                    result = dataTable.ToList<SearchContainerModel>();
                }
            }
            return result;
        }

        [HttpPost]
        public ActionResult DataTableContainerByContNo(SearchContainerModel searchContainerModel)
        {
            DataTableModel dataTableModel = new DataTableModel { CurrentPage = 1, IsDescending = true, PageSize = int.MaxValue, PropertyOrder = "Cont" };
            IList<SearchContainerModel> resultSearch = SearchContainerByContNo(Username, searchContainerModel.Cont);
            dataTableModel.TotalRow = resultSearch.Count;
            ViewBag.Pagination = PageHelper.CreateLink(dataTableModel.CurrentPage, dataTableModel.TotalRow, dataTableModel.PageSize, true);
            return View("_DataTableContainerByContNo", resultSearch);
        }

        [NonAction]
        IList<SearchContainerModel> SearchContainerByKodeBlok(string userId, string blok)
        {
            string kdblok = blok.Trim().ToUpper().Replace(" ", string.Empty);
            IList<SearchContainerModel> result = new List<SearchContainerModel>();
            using (var stackingService = new StackingSoapClient())
            {
                string xml = stackingService.FillContInOutByBlokForStock(userId, kdblok);
                if (!string.IsNullOrEmpty(xml))
                {
                    DataSet dataSet = Converter.ConvertXmlToDataSet(xml);
                    DataTable dataTable = dataSet.Tables[0];
                    result = dataTable.ToList<SearchContainerModel>();
                }
            }
            return result;
        }

        [HttpPost]
        public ActionResult DataTableContainerByKodeBlok(SearchContainerModel searchContainerModel)
        {
            DataTableModel dataTableModel = new DataTableModel { CurrentPage = 1, IsDescending = true, PageSize = int.MaxValue, PropertyOrder = "Cont" };
            IList<SearchContainerModel> resultSearch = SearchContainerByKodeBlok(Username, searchContainerModel.Location);
            dataTableModel.TotalRow = resultSearch.Count;
            ViewBag.Pagination = PageHelper.CreateLink(dataTableModel.CurrentPage, dataTableModel.TotalRow, dataTableModel.PageSize, true);
            return View("_DataTableContainerByBlok", resultSearch);
        }
    }
}

ITI.Survey.Web/ITI.Survey.Web.UI/Views/SearchContainer/SearchContainerByContNo.cshtml

@{
    ViewBag.Title = "Search Container By ContNo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model ITI.Survey.Web.UI.Models.SearchContainerModel


<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <b>SEARCH CONTAINER BY CONT NO</b>
            </div>
            <div class="panel-body">
                <div class="form-horizontal">
                    <div class="row">
                        <div class="col-md-12">
                            <form action="@Url.Action("DataTableContainerByContNo", "SearchContainer")" method="post">
                                @Html.AntiForgeryToken()
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <div class="col-md-3">
                                                @Html.LabelFor(model => model.Cont, htmlAttributes: new { @class = "control-label" })
                                            </div>
                                            <div class="col-md-7">
                                               @Html.TextBoxFor(model => model.Cont, new { @class = "form-control" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                               
                               
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <div class="col-md-3 col-md-offset-3">
                                                <button type="button" class="btn btn-primary btn-search" data-hidden=""
                                                        data-skip=""
                                                        data-property-order="Cont" data-pagesize="@int.MaxValue">
                                                    <span><i class="fa fa-search"></i> Search </span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div class="data-result">
                        @Html.Partial("_dataTableContainerByContNo", new List<ITI.Survey.Web.UI.Models.SearchContainerModel>())
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>

ITI.Survey.Web/ITI.Survey.Web.UI/Views/SearchContainer/SearchContainerByKodeBlok.cshtml

@{
    ViewBag.Title = "Search Container By Blok";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model ITI.Survey.Web.UI.Models.SearchContainerModel

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <b>SEARCH CONTAINER BY Blok</b>
            </div>
            <div class="panel-body">
                <div class="form-horizontal">
                    <div class="row">
                        <div class="col-md-12">
                            <form action="@Url.Action("DataTableContainerByKodeBlok", "SearchContainer")" method="post">
                                @Html.AntiForgeryToken()
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <div class="col-md-3">
                                                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label" })
                                            </div>
                                            <div class="col-md-7">
                                                @Html.TextBoxFor(model => model.Location, new { @class = "form-control" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <div class="col-md-3 col-md-offset-3">
                                                <button type="button" class="btn btn-primary btn-search" data-hidden=""
                                                        data-skip=""
                                                        data-property-order="Cont" data-pagesize="@int.MaxValue">
                                                    <span><i class="fa fa-search"></i> Search </span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div class="data-result">
                        @Html.Partial("_dataTableContainerByBlok", new List<ITI.Survey.Web.UI.Models.SearchContainerModel>())
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>

ITI.Survey.Web/ITI.Survey.Web.UI/Views/SearchContainer/_dataTableContainerByBlok.cshtml

@{
    Layout = null;
}

@model IEnumerable<ITI.Survey.Web.UI.Models.SearchContainerModel>

<div class="col-xs-12">
    <div class="form-group">
        <input type="hidden" class="current-page" value="1" />
        @*<div class="table-responsive">*@
        <table class="table table-striped table-bordered dataTable" width="100%">
            <thead>
                <tr>
                    <th data-id="Cont" data-desc="True">
                        @Html.DisplayNameFor(model => model.Cont)
                    </th>
                    <th data-id="CustomerCode" data-desc="True">
                        @Html.DisplayNameFor(model => model.CustomerCode)
                    </th>
                    <th data-id="Size" data-desc="True">
                        @Html.DisplayNameFor(model => model.Size)
                    </th>
                    <th data-id="Type" data-desc="True">
                        @Html.DisplayNameFor(model => model.Type)
                    </th>
                    
                    <th data-id="Condition" data-desc="True">
                        @Html.DisplayNameFor(model => model.Condition)
                    </th>
                    <th data-id="DtmIn" data-desc="True">
                        @Html.DisplayNameFor(model => model.DtmIn)
                    </th>
                    <th data-id="ActIn" data-desc="True">
                        @Html.DisplayNameFor(model => model.ActIn)
                    </th>
                    <th data-id="Location" data-desc="True">
                        @Html.DisplayNameFor(model => model.Location)
                    </th>
                    <th data-id="ContAge" data-desc="True">
                        @Html.DisplayNameFor(model => model.ContAge)
                    </th>
                    <th data-id="Message" data-desc="True">
                        @Html.DisplayNameFor(model => model.Message)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cont)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CustomerCode)
                        </td> 
                        <td>
                            @Html.DisplayFor(modelItem => item.Size)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Type)
                        </td>
                       
                        <td>
                            @Html.DisplayFor(modelItem => item.Condition)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DtmIn)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ActIn)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Location)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ContAge)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Message)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @*<div class="dt-toolbar-footer">
                    <div class="col-xs-12 col-sm-12">
                        <div class="dataTables_paginate paging_simple_numbers">
                            @Html.Raw(ViewBag.Pagination)
                        </div>
                    </div>
                </div>
            </div>*@
    </div>
</div>

ITI.Survey.Web/ITI.Survey.Web.UI/Views/SearchContainer/_dataTableContainerByContNo.cshtml

@{
    Layout = null;
}

@model IEnumerable<ITI.Survey.Web.UI.Models.SearchContainerModel>

<div class="col-xs-12">
    <div class="form-group">
        <input type="hidden" class="current-page" value="1" />
        <table class="table table-striped table-bordered dataTable" width="100%">
            <thead>
                <tr>
                    <th data-id="Cont" data-desc="True">
                        @Html.DisplayNameFor(model => model.Cont)
                    </th>
                    <th data-id="Cust" data-desc="True">
                        @Html.DisplayNameFor(model => model.CustomerCode)
                    </th>
                    <th data-id="Size" data-desc="True">
                        @Html.DisplayNameFor(model => model.Size)
                    </th>
                    <th data-id="Type" data-desc="True">
                        @Html.DisplayNameFor(model => model.Type)
                    </th>
                    
                    <th data-id="Cond" data-desc="True">
                        @Html.DisplayNameFor(model => model.Condition)
                    </th>
                    <th data-id="DtmIn" data-desc="True">
                        @Html.DisplayNameFor(model => model.DtmIn)
                    </th>
                    <th data-id="ActIn" data-desc="True">
                        @Html.DisplayNameFor(model => model.ActIn)
                    </th>
                    <th data-id="Loc" data-desc="True">
                        @Html.DisplayNameFor(model => model.Location)
                    </th>
                    <th data-id="Age" data-desc="True">
                        @Html.DisplayNameFor(model => model.ContAge)
                    </th>
                    <th data-id="Message" data-desc="True">
                        @Html.DisplayNameFor(model => model.Message)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cont)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CustomerCode)
                        </td> 
                        <td>
                            @Html.DisplayFor(modelItem => item.Size)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Type)
                        </td>
                       
                        <td>
                            @Html.DisplayFor(modelItem => item.Condition)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DtmIn)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ActIn)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Location)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ContAge)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Message)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @*<div class="dt-toolbar-footer">
                    <div class="col-xs-12 col-sm-12">
                        <div class="dataTables_paginate paging_simple_numbers">
                            @Html.Raw(ViewBag.Pagination)
                        </div>
                    </div>
                </div>
            </div>*@
    </div>
</div>