ITI.Survey.Web/ITI.Survey.Web.UI/Controllers/BlokSystemController.cs
using ITI.Survey.Web.UI.Models;
using System.Linq;
using System.Web.Mvc;
using AGY.Solution.Helper.Common;
using ITI.Survey.Web.UI.StackingWebService;

namespace ITI.Survey.Web.UI.Controllers
{

    [Authorize]
    public class BlokSystemController : BaseController
    {
        // GET: BlokSystem
        public ActionResult Index()
        {
            BlokSystemModel model = new BlokSystemModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult GoByContainerNumber(string contNo)
        {
            string resultMessage = string.Empty;
            ContInOutModel contInOutModel = new ContInOutModel();
            BlokSystemModel blokSystemmodel = new BlokSystemModel();
            using (var stackingService = new StackingSoapClient())
            {
                string contNoText = contNo.Trim();
                contNoText = contNoText.Replace(" ", "");
                if (contNoText.Length <= 0)
                {
                    return View(contNo);
                }
                blokSystemmodel.ContNo = contNoText.Substring(0, 4) + " " +
                    contNoText.Substring(4, 3) + " " + contNoText.Substring(7, 3) + " " + contNoText.Substring(10, 1);

                string contIntOutXML = string.Empty;
                contIntOutXML = stackingService.FillContInOutByContainerNumber(Username, blokSystemmodel.ContNo.ToUpper());
                if (!string.IsNullOrEmpty(contIntOutXML))
                {
                    var dsContInOut = Converter.ConvertXmlToDataSet(contIntOutXML);
                    var listContIntOut = dsContInOut.Tables[0].ToList<ContInOutModel>();
                    contInOutModel = listContIntOut.FirstOrDefault();

                }
                else
                {
                    blokSystemmodel.ResultMessage = blokSystemmodel.ContNo + " tidak ditemukan.";
                    return View(blokSystemmodel);
                }
                blokSystemmodel.ResultMessage = contInOutModel.Cont + "\r\n";
                blokSystemmodel.Size = contInOutModel.Size;
                blokSystemmodel.ContInOutId = contInOutModel.ContInOutId;
                blokSystemmodel.Cont = contInOutModel.Cont;
                blokSystemmodel.Shipper = contInOutModel.CustomerCode;
                if (contInOutModel.Location.Length == 0 || contInOutModel.Location.Contains("TMP"))
                {
                    blokSystemmodel.ResultMessage += "Lokasi : Belum di set\r\n";
                }
                else
                {
                    blokSystemmodel.ResultMessage += "Lokasi : " + contInOutModel.Location.Substring(0, 1) + "  " +
                                                  contInOutModel.Location.Substring(1, 2) + "  " +
                                                  contInOutModel.Location.Substring(3, 2) + "  " +
                                                  contInOutModel.Location.Substring(5, 1) + "\r\n";
                }
                blokSystemmodel.ResultMessage += "Silakan input lokasi baru.";

            }

            return Json(blokSystemmodel, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Process(BlokSystemModel model, UserData userData)
         {
            model.BlokSystemValidate(ModelState);
            if (!ModelState.IsValid)
            {
                return Json(new { errorList = GetErrorList(ModelState) }, JsonRequestBehavior.AllowGet);
            }

            string _kodeBlok = model.Blok.ToUpper() + model.Bay + model.Row + model.Tier;

            var status = false;
            try
            {
                using (var stackingService = new StackingSoapClient())
                {
                    var contIntOutXML = stackingService.FillContInOutByContainerNumber(Username, model.ContNo);
                    var contInOutModel = new ContInOutModel();
                    if (!string.IsNullOrEmpty(contIntOutXML))
                    {
                        var dsContInOut = Converter.ConvertXmlToDataSet(contIntOutXML);
                        var listContIntOut = dsContInOut.Tables[0].ToList<ContInOutModel>();
                        contInOutModel = listContIntOut.FirstOrDefault();

                    }
                    else
                    {
                        return Json(new { errorList = GetErrorList(ModelState) }, JsonRequestBehavior.AllowGet);
                    }
                    if (_kodeBlok.Length < 6)
                    {
                        status = false;
                        model.ResultMessage = "Lokasi kurang dari 6 digit";
                        return Json(new { Status = status, Message = model.ResultMessage }, JsonRequestBehavior.AllowGet);

                    }

                    model.ContInOutId = contInOutModel.ContInOutId;
                    model.Cont = contInOutModel.Cont;
                    model.Shipper = contInOutModel.CustomerCode;
                    model.Size = contInOutModel.Size;
                    model.ResultMessage = contInOutModel.Message;
                    model.ActiveUser = Username;
                    model.Location = _kodeBlok;
                    model.KodeBlok = _kodeBlok;

                    // User data from login
                    model.EqpId = userData.HEID;
                    model.OPID = userData.OPID;

                    var kodeBlok = model.Blok.ToUpper() + model.Bay + model.Row + model.Tier;
                    model.FlagAct = "MOVE";
                    // Logical Process
                    if (model.SideChoose.ToUpper() == "KIRI" || model.SideChoose == string.Empty)
                    {
                        model.Cont = model.Cont;
                        model.Cont2 = "";
                    }
                    else
                    {
                        model.Cont2 = model.Cont;
                        model.Cont = string.Empty;
                    }

                    model.ResultMessage = stackingService.SubmitBlokMove(Converter.ConvertToXML(model));
                    if (model.ResultMessage.Contains("Error"))
                    {
                        status = false;
                    }
                    else
                    {
                        status = true;
                        model.ResultMessage = model.ResultMessage = model.ContNo + "\r\nDipindahkan ke : " + model.Location;
                        model.Cont = string.Empty;
                        model.Blok = string.Empty;
                        model.Bay = string.Empty;
                        model.Row = string.Empty;
                        model.Bay = string.Empty;
                    }
                    return Json(new { Status = status, Message = model.ResultMessage }, JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json(new { Status = status, Message = model.ResultMessage }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

ITI.Survey.Web/ITI.Survey.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Survey Web">
    <meta name="author" content="AGY Solution">

    <title class="text-capitalize">@ViewBag.Title - SURVEY</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="~/Content/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="~/Content//vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="~/Content//vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="~/Content/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="~/Content/vendor/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/Content/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- Website CSS -->
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script type="text/javascript">
        function preventBack() { window.history.forward(); }
        setTimeout("preventBack()", 0);
        window.onunload = function () { null };
    </script>
</head>
<body onload="loading()">
    <div id="divLoading" style="display: none;">
        <div id="loadingposition" style="position: absolute; left: 42%; top: 42%; z-index: 1055;">
            <img src="~/Content/img/Loading_icon.gif" alt="Processing" style="vertical-align: middle; width: 80px;" />
        </div>
    </div>
    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Home")">Survey Application</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right text-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#"><i class="fa fa-user fa-fw"></i> @ViewBag.CurrentUserName</a>
                        </li>
                        @*<li>
                            <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                            </li>*@
                        <li class="divider"></li>
                        <li>
                            <a id="btn-logout" href="#" data-href="@Url.Action("LogOff", "Account")"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard fa-fw"></i>HOME</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","ContainerDuration")">CONTAINER DURATION</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","MuatContainer")">MUAT CONTAINER</a>
                        </li>
                        <li>
                            <a href="@Url.Action("BongkarContainerAV","BongkarContainer")">BONGKAR CONTAINER AV</a>
                        </li>
                        <li>
                            <a href="@Url.Action("BongkarContainerDM","BongkarContainer")">BONGKAR CONTAINER DM</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","InputNoMobil")">INPUT NOMOR MOBIL</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","BlokSystem")">BLOK SYSTEM</a>
                        </li>
                        <li>
                            <a href="@Url.Action("SearchContainerByContNo","SearchContainer")">SEARCH BY CONTAINER</a>
                        </li>
                        <li>
                            <a href="@Url.Action("SearchContainerByKodeBlok","SearchContainer")">SEARCH BY BLOK</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-xs-12">
                    @RenderBody()
                </div>
            </div>
            <!-- /.row -->

            <div class="footer text-center">
                &copy; 2018
            </div>
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->

    <div class="confirmationdialog" title="Confirmation" style="display: none;">
        <p>
            <label class="control-label confirm-message"></label>
        </p>
    </div>
    <div class="notificationdialog" title="Notification" style="display: none;">
        <p>
            <label class="control-label notif-message"></label>
        </p>
    </div>

    <input type="hidden" id="AccessDeniedURL" value="@Url.Action("Login","Account")" />
    <input type="hidden" id="ErrorURL" value="@Url.Action("Login","Account")" />

    <!-- jQuery -->
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Scripts/jquery-2.2.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.11.4.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Content/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="~/Content/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="~/Content/vendor/datatables-responsive/dataTables.responsive.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="~/Content/vendor/raphael/raphael.min.js"></script>
    <script src="~/Content/vendor/morrisjs/morris.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="~/Content/dist/js/sb-admin-2.js"></script>
    <script src="~/Scripts/CustomScript.js"></script>
    <script src="~/Scripts/jquery.form.js"></script>
    <script src="~/Scripts/LINQ_JS.js"></script>

    @RenderSection("scripts", false)
</body>
</html>

ITI.Survey.Web/ITI.Survey.Web.UI/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewBag.Title</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="~/Content/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/Content/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <script type="text/javascript">
        function preventBack() { window.history.forward(); }
        setTimeout("preventBack()", 0);
        window.onunload = function () { null };
    </script>
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <!-- jQuery -->
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Scripts/jquery-2.2.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.11.4.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Content/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="~/Content/dist/js/sb-admin-2.js"></script>

    <script>
        $.fn.showErrorModelState = function () {
            window.scrollTo(0, 0);
            $('form > div > ul > li').click(function () {
                //$('[data-val-required="' + $(this).html() + '"]').focus();
                if ($('[name="' + $(this).attr('key') + '"]').hasClass('ckeditor')) jQuery('.cke_wysiwyg_frame').contents().find('body').focus();
                else
                    $('[name="' + $(this).attr('key') + '"]').focus();
            });
            $('form > div > div > ul > li').click(function () {
                //$('[data-val-required="' + $(this).html() + '"]').focus();
                if ($('[name="' + $(this).attr('key') + '"]').hasClass('ckeditor')) jQuery('.cke_wysiwyg_frame').contents().find('body').focus();
                else
                    $('[name="' + $(this).attr('key') + '"]').focus();
            });
        }

        $(document).ready(function () {
            $(".form-control").keyup(function (event) {
                if (event.keyCode == 13) {
                    doLogin();
                }
            });
            $('#btnLogin').click(function () {
                doLogin();
            });
        });
        function doLogin() {
            $.ajax({
                url: $("#formLogin").attr('action'),
                data: $("#formLogin").serialize(),
                dataType: 'json',
                type: 'post',
                //beforeSend: function () {
                //    $('#formApprovalChecker').showloading();
                //},
                //complete: function () {
                //    $('#formApprovalChecker').hideloading();
                //},
                success: function (result) {
                    if (result.Status == true) {
                        if (result.ReturnUrl != undefined) {
                            if (result.ReturnUrl == '/')
                                window.location = "@Url.Action("Index", "Home")";
                            window.location = result.ReturnUrl;
                        }
                    }
                    else {
                        if (result.errorList != undefined) {
                            var errorResult = '';
                            errorResult += "<div class='validation-summary-errors' data-valmsg-summary='true'><ul>";
                            $.each(result.errorList, function (i, value) {
                                errorResult += "<li style='cursor: pointer; color: red; list-style-type: square; margin-left: 15px;' key='" + value.Key + "'>" + value.ErrorMessage + "</li>";
                            });
                            errorResult += "</ul></div>";

                            $('#ErrorSummary', $("#formLogin")).html(errorResult);
                            $(window).showErrorModelState();
                        }
                        else {
                            $('#ErrorLogin').text(result.ErrorMessage);
                            if (result.ReturnUrl != undefined) {
                                window.location = result.ReturnUrl;
                            }
                            else {
                                return;
                            }
                        }
                    }
                }
            });
        }
    </script>
</body>
</html>